//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int ClientID { get; set; }
        public string ClientRS { get; set; }
        public string ClientRC { get; set; }
        public string ClientNIS { get; set; }
        public string ClientNIF { get; set; }
        public string ClientAI { get; set; }
        public string ClientAddress { get; set; }
        public string ClientTel { get; set; }
        public string ClientMobile { get; set; }
        public string ClientFix { get; set; }
        public string ClientFax { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public Nullable<int> ClientTypeID { get; set; }
        public Nullable<System.DateTime> ClientInsertionDate { get; set; }
        public string ClientEmail { get; set; }
        public string ClientDescription { get; set; }
        public Nullable<int> ClientProfessionID { get; set; }
    }
}
