//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int CommandID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
