//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture()
        {
            this.Factures1 = new HashSet<Facture>();
        }
    
        public int FactureID { get; set; }
        public Nullable<int> OrdresID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FactureNum { get; set; }
        public Nullable<System.DateTime> FactureDate { get; set; }
        public Nullable<int> TVAID { get; set; }
        public string TypePayment { get; set; }
        public Nullable<int> FactureFather { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Status { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Factures1 { get; set; }
        public virtual Facture Facture1 { get; set; }
        public virtual Order Order { get; set; }
        public virtual TVA TVA { get; set; }
    }
}
