//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GcdbEntities : DbContext
    {
        public GcdbEntities()
            : base("name=GcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Command> Commands { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DatabaseLog> DatabaseLogs { get; set; }
        public virtual DbSet<DocModel> DocModels { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<ProductMeasure> ProductMeasures { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductState> ProductStates { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseStore> PurchaseStores { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockStore> StockStores { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Telephone> Telephones { get; set; }
        public virtual DbSet<TVA> TVAs { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<clientprovidertype> clientprovidertypes { get; set; }
        public virtual DbSet<profession> professions { get; set; }
        public virtual DbSet<servicefacture> servicefactures { get; set; }
        public virtual DbSet<servicefacturestore> servicefacturestores { get; set; }
        public virtual DbSet<servicemodel> servicemodels { get; set; }
        public virtual DbSet<ventefacture> ventefactures { get; set; }
        public virtual DbSet<ventemodel> ventemodels { get; set; }
    }
}
