//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PurchaseStores = new HashSet<PurchaseStore>();
            this.StockStores = new HashSet<StockStore>();
            this.ProductMeasures = new HashSet<ProductMeasure>();
            this.ProductStates = new HashSet<ProductState>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string productType { get; set; }
        public string MeasureUnit { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ProductMinQte { get; set; }
        public Nullable<int> ProductMaxQte { get; set; }
        public Nullable<int> UnitsOnOrder { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public byte[] Photo { get; set; }
        public string ReferenceInterne { get; set; }
        public string ReferenceExterne { get; set; }
        public string Designation { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseStore> PurchaseStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockStore> StockStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMeasure> ProductMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductState> ProductStates { get; set; }
    }
}
