//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class profession
    {
        public int ProfessionID { get; set; }
        public string professionName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> InsertionDate { get; set; }
    }
}
