//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseStore
    {
        public int PurchaseStoreID { get; set; }
        public int PurchaseID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> StockStoreID { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> UnitsOnOrder { get; set; }
        public Nullable<double> TotalPriceAchat { get; set; }
        public Nullable<double> VentePriceGros { get; set; }
        public Nullable<double> VentePriceDetail { get; set; }
        public Nullable<double> VentePriceComptoire { get; set; }
        public Nullable<float> Discount { get; set; }
        public Nullable<double> TvaValue { get; set; }
        public string RefrenceNum { get; set; }
        public string Observation { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual StockStore StockStore { get; set; }
    }
}
