//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceFamilly { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<System.DateTime> ServiceInsertionDate { get; set; }
    }
}
