//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicefacturestore
    {
        public int ServiceFactureStoreID { get; set; }
        public Nullable<int> ServiceFactureID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceFamille { get; set; }
        public Nullable<double> ServicePriceHT { get; set; }
        public Nullable<int> ServiceQte { get; set; }
        public Nullable<double> ServiceTva { get; set; }
        public string ServiceDescription { get; set; }
    }
}
