//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicefacture
    {
        public int ServiceFactureID { get; set; }
        public Nullable<System.DateTime> ServiceFactureDate { get; set; }
        public string ServiceFactureType { get; set; }
        public string ServiceModePayment { get; set; }
        public string ServiceEtatPayement { get; set; }
        public Nullable<double> ServiceTvaValue { get; set; }
        public string ServiceClientFullName { get; set; }
        public string ServiceCommandeNumber { get; set; }
        public Nullable<System.DateTime> ServiceCommandeDate { get; set; }
    }
}
