//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingsID { get; set; }
        public string CompanyName { get; set; }
        public string Adresse { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string MobPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string RC { get; set; }
        public string NF { get; set; }
        public string NIS { get; set; }
        public string AI { get; set; }
        public string PassWordApp { get; set; }
        public Nullable<bool> FirstTime { get; set; }
        public string Licence { get; set; }
        public Nullable<System.DateTime> DateMAJ { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FactureNumber { get; set; }
        public string FactureProNumber { get; set; }
        public Nullable<System.DateTime> DateFirstTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
