//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale.DomainModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockStore()
        {
            this.PurchaseStores = new HashSet<PurchaseStore>();
        }
    
        public int StockStoreID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> StockID { get; set; }
        public string ProductState { get; set; }
        public string RefrenceNum { get; set; }
        public string Serialnumber { get; set; }
        public string StockageID { get; set; }
        public Nullable<System.DateTime> DateOfStartPremption { get; set; }
        public Nullable<System.DateTime> DateOfEndPremption { get; set; }
        public Nullable<System.DateTime> InsertionDate { get; set; }
        public Nullable<double> TotalPriceAchat { get; set; }
        public Nullable<double> UnitsOnOrder { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> VentePriceGros { get; set; }
        public Nullable<double> VentePriceDetail { get; set; }
        public Nullable<double> VentePriceComptoire { get; set; }
        public Nullable<double> TvaValue { get; set; }
        public Nullable<float> Discount { get; set; }
        public string Observation { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseStore> PurchaseStores { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
